#!/bin/bash

# Show an extremely abbreviated summary of the current account line balances and
# XRP balance. Account can be provided on the command line or stored in a file
# called "ripple-account.txt" in the same directory that this script runs from.

accountfile="$( dirname $0 )/ripple-account.txt"
if [ -r ${accountfile} ]
then
  defaultaccount=$(cat ${accountfile})
else
  defaultaccount=rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh
fi

RIPPLED=${1:-~/dev/rippled-upstream/build/gcc.debug/rippled}
RPC_PORT=${2:-5015}
account=${3:-${defaultaccount}}

# echo $account
${RIPPLED} -q \
  --rpc_ip=127.0.0.1 --rpc_port=${RPC_PORT} account_lines ${account} "" \
    validated | egrep 'balance|currency|index|error' \
  && ${RIPPLED} -q \
    --rpc_ip=127.0.0.1 --rpc_port=${RPC_PORT} account_info ${account} validated \
      | egrep 'Balance|PreviousTxnLgrSeq|error'
