#!/bin/bash

# Show an extremely abbreviated summary of the current account line balances and
# XRP balance. Account can be provided on the command line or stored in a file
# called "ripple-account.txt" in the same directory that this script runs from.

accountfile="$( dirname $0 )/ripple-account.txt"
if [ -r ${accountfile} ]
then
  defaultaccount=$(cat ${accountfile})
else
  defaultaccount=rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh
fi

RIPPLED=${1:-$( dirname $0 )/rippled}
RPC_IP=${2:-127.0.0.1}
RPC_PORT=${3:-51235}
account=${4:-${defaultaccount}}

name()
{
  curl https://data.ripple.com/v2/gateways/$1 2>/dev/null | \
    json_pp | \
      awk '(/"name"/) { print $3; }'
}

# echo $account
${RIPPLED} -q \
  --rpc_ip=${RPC_IP} --rpc_port=${RPC_PORT} account_lines ${account} "" \
    validated | egrep 'balance|currency|account|index|limit|quality|error' \
    | awk '{ sub(/^ */, ""); gsub(/[,"]/, "", $3); } 
      ( /account/ ) { account = $3; }
      ( /balance/ ) { balance = $3; }
      ( /limit/ && $3 > limit ) { limit = $3; }
      ( /currency/ ) { currency = $3; }
      (/quality_out/ && account !~ /(rMAz5ZnK73nyNUL4foAvaxdreczCkG3vA6)/ && currency !~ /0158415500000000C1F76FF6ECB0BAC600000000/ ) { print currency " / " account " : " balance " / " limit; }
      ( balance == "" && account == "" ) { print; }
      ( /quality_out/ ) { balance=""; account=""; limit=0; }' \
  && ${RIPPLED} -q \
    --rpc_ip=${RPC_IP} --rpc_port=${RPC_PORT} account_info ${account} validated \
      | jq -j 'if .error then .
        else { "Balance" : .result.account_data.Balance,
        "PreviousTxnLedgerSeq" : .result.account_data.PreviousTxnLgrSeq }
        end'
