#!/bin/bash

set -e
# set -x

cmake_prefix=./build/cmake/
cmake_dirs=$(\ls -r ${cmake_prefix})
echo Dirs: ${cmake_dirs}
cmake_targets="rippled"
echo Targets: ${cmake_targets}
rundir=$(\ls -r ${cmake_prefix} | head -1)
echo rundir: ${rundir}

gdb=""
gdbextra=""
clean=0
fast=0
test=0
while [[ ${#@} > 0 ]]
do
  if [[ "$1" == "fast" ]]
  then
    shift
    fast=1
  elif [[ "$1" == "debug" ]]
  then
    shift
    gdb="gdb -q -ex 'tui enable' -ex 'winheight src -8' -ex 'set pagination off' "
    gdbextra="--fg"
  elif [[ "$1" == "test" ]]
  then
    shift
    test=1
  elif [[ "$1" == "clean" ]]
  then
    shift
    clean=1
  elif [[ ${#gdb} > 0 && "$1" == "--" ]]
  then
    shift
    if [[ "${#@}" ]]
    then
      gdb="${gdb} ${@} "
      shift "${#@}"
    fi
  elif [[ -d "${cmake_prefix}$1" ]]
  then
    rundir="$1"
    echo rundir changed to: ${rundir}
    shift
  else
    echo "Unknown option: $1" 1>&2
    exit 127
  fi
done

if [[ ${#gdb} > 0 ]]
then
  gdb="${gdb} -ex run -ex quit --args"
fi

nproc=$(nproc)

time (
  set -o pipefail
  rm -fv build/testrun.out
  if [[ ${clean} != 0 ]]
  then
    for dir in ${cmake_dirs}
    do
      dir=${cmake_prefix}${dir}
      cmake --build $dir --target clean |& tee -a build/testrun.out || exit 1
    done
  fi

  # Determine if parallel unit tests are enabled.
  parallel_test=''

  set -x
  dir=${cmake_prefix}${rundir}
  cmake --build $dir -- -j${nproc} |& tee -a build/testrun.out || exit 1
  parallel_test=$( $dir/rippled --help |& grep -q unittest-jobs && \
    echo "--testjobs=${nproc}" )
  set +x

  echo Parallel: ${parallel_test} |& tee -a build/testrun.out

  # CMake
  if [[ ${fast} != 0 ]]
  then
    for dir in ${cmake_dirs}
    do
      dir=${cmake_prefix}${dir}
      for target in ${cmake_targets}
      do
        echo Building $target in $dir |& tee -a build/testrun.out
        cmake --build $dir --target $target -- -j${nproc} \
          |& tee -a build/testrun.out || exit 1
      done
    done || exit 1
  else
    set -x
    ./Builds/Test.py -v -q --dir ${cmake_dirs} --target ${cmake_targets} \
      ${parallel_test} -- -j${nproc} |& tee build/testrun.out || exit 1
    set +x
  fi

) || exit 1

if [[ ${test} != 0 ]]
then
  exit 0
fi

set -x

if [ -e ~/rippled/debug.log ]
then
  mv -vi ~/rippled/debug.log{,.$(date '+%s')} || true
fi
if [ -e ~/rippled/logs/debug.log ]
then
  mv -vi ~/rippled/logs/debug.log{,.$(date '+%s')} || true
fi
gnome-terminal -- tmux new-session -A -s rippled -x 80 -y 30 sleep 600
# Give the terminal a few seconds to create
sleep 2
for network in rippled # rippled-altnet
do
  if [ -e ~/${network}/debug.log ]
  then
    mv -vi ~/${network}/debug.log{,.$(date '+%s')} || true
  fi
  if [ -e ~/.config/ripple/${network}.cfg ]
  then
    # Stop the currently running rippled, if any
    tmux new-window -a -t rippled \
      "${cmake_prefix}${rundir}/rippled \
      --conf ~/.config/ripple/${network}.cfg stop"
    # Start the new rippled
    tmux new-window -a -t rippled "${gdb} \
      ${cmake_prefix}${rundir}/rippled \
      --conf ~/.config/ripple/${network}.cfg --net ${gdbextra}"
      : 'https://sourceware.org/gdb/onlinedocs/gdb/TUI-Commands.html'
      : 'C-x a'
  fi
done

grep failures build/testrun.out
