#!/bin/bash

set -e

gdb=""
gdbextra=""
clean=0
fast=0
cmake=0
test=0
while [[ ${#@} > 0 ]]
do
  if [[ "$1" == "fast" ]]
  then
    shift
    fast=1
  elif [[ "$1" == "cmake" ]]
  then
    shift
    cmake=1
  elif [[ "$1" == "debug" ]]
  then
    shift
    gdb="gdb -q --tui "
    gdbextra="--fg"
  elif [[ "$1" == "test" ]]
  then
    shift
    test=1
  elif [[ "$1" == "clean" ]]
  then
    shift
    clean=1
  elif [[ ${#gdb} > 0 && "$1" == "--" ]]
  then
    shift
    if [[ "${#@}" ]]
    then
      gdb="${gdb} ${@} "
      shift "${#@}"
    fi
  else
    echo "Unknown option: $1" 1>&2
    exit 127
  fi
done

if [[ ${#gdb} > 0 ]]
then
  gdb="${gdb} -ex run -ex quit --args"
fi

cmake_prefix=./build/cmake/
cmake_dirs=$(\ls ${cmake_prefix})
echo Dirs: ${cmake_dirs}
cmake_targets="rippled rippled_classic"
echo Targets: ${cmake_targets}
sconstarget="debug release"
echo Scons targets: ${sconstarget}

time (
  if [[ ${clean} != 0 ]]
  then
    for dir in ${cmake_dirs}
    do
      dir=${cmake_prefix}${dir}
      cmake --build $dir --target clean || exit 1
    done

    # This is ugly and dangerous, but that's scons for ya.
    rm -rf build/{gcc,clang,msvc,proto}*
  fi

  # Determine if parallel unit tests are enabled.
  parallel_test=''
  for dir in ${cmake_dirs}
  do
    dir=${cmake_prefix}${dir}
    cmake --build $dir -- -j8 || exit 1
    parallel_test=$( $dir/rippled --help |& grep -q unittest-jobs && \
      echo '--testjobs=8' )
    # There's probably a smarter way to just get the first one, but lazy
    break
  done
  echo Parallel: ${parallel_test}

  # CMake
  if [[ ${fast} != 0 ]]
  then
    for dir in ${cmake_dirs}
    do
      dir=${cmake_prefix}${dir}
      for target in ${cmake_targets}
      do
        echo Building $target in $dir
        cmake --build $dir --target $target -- -j8 || exit 1
      done
    done || exit 1
  else
    ./Builds/Test.py -q -v --dir ${cmake_dirs} --target ${cmake_targets} \
      ${parallel_test} -- -j8 || exit 1
  fi

  # scons
  if [[ ${cmake} == 0 ]]
  then
    if [[ ${fast} != 0 ]]
    then
      scons -j 8 --assert \
        $sconstarget \
          || exit 1
    else
      ./Builds/Test.py -q -v ${parallel_test} -- -j 8 --assert \
        $sconstarget \
          || exit 1
    fi
  fi
) || exit 1

if [[ ${test} != 0 ]]
then
  exit 0
fi

set -x

if [ -e ~/rippled/debug.log ]
then
  mv -vi ~/rippled/debug.log{,.$(date '+%s')} || true
fi
gnome-terminal --geometry=80x30 -- tmux new-session -A -s rippled -x 80 -y 30 sleep 600
for dir in rippled # rippled-altnet
do
  if [ -e ~/${dir}/debug.log ]
  then
    mv -vi ~/${dir}/debug.log{,.$(date '+%s')} || true
  fi
  if [ -e ~/.config/ripple/${dir}.cfg ]
  then
    tmux new-window -t rippled "${gdb} \
      ./build/cmake/gcc.debug/rippled \
      --conf ~/.config/ripple/${dir}.cfg --net ${gdbextra}"
  fi
done
