#!/bin/bash

seconds()
{
  date --date="${1}" +%s
}

rippleepoch=$( seconds "Sat Jan  1 12:00:00 AM UTC 2000" )
if [ $# = 0 ]
then
  time="now"
elif [ $# = 1 ] && [ "$1" -eq "$1" ] 2>/dev/null
then
  time="@$[ $1 + $rippleepoch ]"
  echo "Input ripple time: $1"
else
  time="$*"
  echo "Input wall time: ${time}"
fi

seconds=$( seconds "${time}" )
echo -n "Local time: "
date --date="@${seconds}"
echo -n "UTC time: "
date --utc --date="@${seconds}"
echo "Ripple time: " $[ $seconds - $rippleepoch ]

