#!/bin/bash

RIPPLED=${1:-$( dirname $0 )/rippled}
RPC_IP=${2:-127.0.0.1}
RPC_PORT=${3:-51235}

${RIPPLED} -q --rpc_ip=${RPC_IP}:${RPC_PORT} server_info | \
  jq '( .result.info | del(.load) | del(.state_accounting) |
    del(.reporting) | del(.ports) ) // .'
