#! /bin/bash

if test ${#@} -eq 0
then
  echo "Usage: $(basename $0) filename [...]"
  exit 1
fi

files=( "${@}" )
shift

size() { stat --format="%s" "${files[@]}"; }

until size > /dev/null
do
  sleep 1
done

any()
{
  op=$1
  for (( i=0; i<${#newsize[@]}; i=$i+1 ))
  do
    if eval "[[ ${newsize[$i]} $op ${oldsize[$i]:-0} ]]"
    then
      true
      return
    fi
  done
  false
}

oldsize=()
newsize=( $(size) )

while any -ge
do
  if any -gt
  then
    date
    ls -l "${files[@]}"
    sleep 1
  fi
  oldsize=( "${newsize[@]}" )
  newsize=( $(size) )
done
